### ISSUE TITLE
Column grabber does not exist

### ISSUE THREAD

**Issue by tinywombat765** [FRC-3637-Daleks/PitScoutingApp#1]
If anyone knows android could they review my code add tell me why when I submit a database change it says that the table robot does not have a column called grabber?

**Comment by jbott** [comment]
Are you meaning when you click submit in the main view? You make want to take a look at https://github.com/FRC-3637-Daleks/PitScoutingApp/blob/master/app/src/main/java/com/team3637/pitscoutingapp/RobotsDataSource.java#L16 though, as your cursor does not select all columns you are passing in.

**Comment by tinywombat765** [comment]
I do not believe that is the root of the problem but something I need to fix.  Thankyou

**Comment by jbott** [comment]
Have you tried clearing app data? I was not getting any error on a clean install. That leads me to believe your table on disk has schema that does not match your model, which should reflect itself to an error similar to what you are getting.

If that doesn't fix it, can you attach your stack trace? I was unable to reproduce it.

**Comment by tinywombat765** [comment]
I uninstalled the app from my phone, cleaned the project, rebuild the app, then reinstalled it on my phone, and now it works.
Thank you John!
